---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller-example
  labels:
    app: replication-controller-example
spec:
  replicas: 3
  template:
    metadata:
      name: example-pod
      labels:
        app: example-pod
    spec:
      containers:
        - name: example-con
          image: nginx
