apiVersion: v1
kind: LimitRange
metadata:
  name: max-min-limit-range
spec:
  limits:
  - default:
      cpu: 1
      memory: 200Mi
    defaultRequest:
      cpu: 0.5
      memory: 100Mi
    max:
      cpu: 2
      memory: 1Gi
    min:
      cpu: 0.5
      memory: 50Mi
    type: Container
