---
apiVersion: v1
kind: Pod
metadata:
  name: pod-example-file
  labels:
    name: pod-example-file
spec:
  containers:
    - name: con-example-file
      image: busybox
      command:
        - /bin/ash
        - -c
        # TODO: cat does not print password.secret to stdout
        - "cat /home/password.secret && sleep 10000"
      volumeMounts:
        - mountPath: /home
          name: secret-vol
  volumes:
    - name: secret-vol
      secret:
        secretName: file-secret-example
