---
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    name: pod-example
spec:
  containers:
    - name: con-example
      image: busybox
      command:
        - /bin/ash
        - -c
        - "printenv USERNAME && sleep 10000"
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: username
