---
kind: Service
apiVersion: v1
metadata:
  name: example-service
spec:
  selector:
    app: example-deployment
  type: NodePort
  ports:
    - name: port-of-nginx
      port: 80
      targetPort: 8080
      nodePort: 30020
