---
apiVersion: v1
kind: Pod
metadata:
  name: pod-example-inject-all
  labels:
    name: pod-example-inject-all
spec:
  containers:
    - name: con-example
      image: busybox
      command:
        - /bin/ash
        - -c
        - "printenv author && sleep 10000"
      envFrom:
        - configMapRef:
            name: config-map-example
